'use client'

import './globals.css'

import '@rainbow-me/rainbowkit/styles.css';
import {
  getDefaultWallets,
  RainbowKitProvider,
} from '@rainbow-me/rainbowkit';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import {
  mainnet,
  polygon,
  optimism,
  arbitrum,
  zora,
} from 'wagmi/chains';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'
import NavBar from './components/NavBar'

import { Providers } from './providers';


const inter = Inter({ subsets: ['latin'] })


// export const metadata: Metadata = {
//   title: 'Quantum Fair',
//   description: 'Generated by shadow',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
        </body>
    </html>
  )
}
